### ISSUE TITLE
[Suggestion] add some showcase and documentation

### ISSUE THREAD

**Issue by RishiVora** [yassineibr/dotfiles#145]
Heyy, I stumbled upon your dots when I was looking through GitHub trying to find someone who had some basic implementation of [astal](https://github.com/aylur/astal) in Nix. But I found much more in here. I have been using NixOS for a while and really appreciate your dots.

I hope that you showcase your setup and put some minimal documentation (totally your wish) on what all you have in your config. For now, I have borrowed your waybar; it was just what I was looking for. Cheers! :beers:

**Comment by yassineibr** [comment]
Thanks for the suggestions, i am still learning nix, and i don't have something to showcase, for now. but in the futur i might post some screenshots of the setup. 
Thanks again for the suggestions
